docker-compose.yml
=> Prevent login errors in Docker environment

.github/workflows/check-installation.yml, .github/workflows/security-secrets.yml, .pre-commit-config.yaml, .secrets.baseline
Check default credentials in Docker environments in different OS using GitHub Actions.
=> Test Rekono installation in CI/CD

.secrets.baseline, rekono/defectdojo/api.py, rekono/findings/nvd_nist.py, rekono/rekono/settings.py, rekono/testing/api/external/test_nvd_nist.py, rekono/testing/executions/test_base_tool.py, rekono/testing/mocks/nvd_nist.py
- Prevent unexpected errors in Defect-Dojo and NVD NIST API requests
- Prevent rate limit in NVD NIST API requests
=> Retry mechanism for external API requests

requirements.txt
Upgrade Django version to 3.2.16
=> Fix vulnerability SNYK-PYTHON-DJANGO-3039675

rekono/frontend/src/modals/Target.vue, requirements.txt
=> Create multiple targets at the same time

rekono/frontend/src/components/project/Tasks.vue, rekono/frontend/src/modals/Target.vue, rekono/frontend/src/modals/Task.vue
=> Execute tasks against multiple targets

docker-compose.yml, docker/rekono/Dockerfile, rekono/frontend/src/backend/RekonoApi.vue, rekono/frontend/src/views/Settings.vue
- Optimize frontend container to build the application when the Docker image is built.
- Upgrade `node` base image to version `18.9.1-alpine` fo fix vulnerabilities: [SNYK-UPSTREAM-NODE-3035795](https://security.snyk.io/vuln/SNYK-UPSTREAM-NODE-3035795) and [SNYK-UPSTREAM-NODE-3035792](https://security.snyk.io/vuln/SNYK-UPSTREAM-NODE-3035792)
=> Optimize Docker environment

rekono/frontend/src/backend/RekonoApi.vue, rekono/frontend/src/backend/tokens.js, rekono/frontend/src/common/MainHeader.vue, rekono/frontend/src/store/index.js
`sessionStorage` has some security advantages against `localStorage`, like the time life of the stored information.
=> Replace localStorage by sessionStorage

rekono/frontend/src/views/Settings.vue, rekono/telegram_bot/bot.py, rekono/telegram_bot/management/commands/telegram_bot.py, rekono/telegram_bot/token.py
Check if Telegram token is configured periodically, to start Telegram bot automatically. So that, the manual Telegram bot startup isn't needed.
=> Deploy Telegram bot automatically after configure the Telegram token

rekono/api/fields.py, rekono/api/views.py, rekono/authentications/serializers.py, rekono/authentications/views.py, rekono/executions/views.py, rekono/findings/views.py, rekono/processes/serializers.py, rekono/processes/views.py, rekono/projects/serializers.py, rekono/projects/views.py, rekono/resources/views.py, rekono/system/serializers.py, rekono/targets/views.py, rekono/tasks/views.py, rekono/tools/serializers.py, rekono/tools/views.py, rekono/users/views.py
=> Optimize API handlers

.github/workflows/unit-testing.yml, requirements.txt
Fix following Regular Expression Denial of Service (ReDoS)vulnerabilities reported by Snyk:
1. https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3180412 (High severity)
2. https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3113904 (Low severity)
=> Upgrade setuptools to version 65.6.3

rekono/frontend/src/modals/Task.vue, rekono/resources/apps.py, rekono/resources/fixtures/1_wordlists.json, rekono/telegram_bot/conversations/ask.py, rekono/telegram_bot/conversations/selection.py
- Add more wordlists by default
- Save file size for wordlists by default during the database migration
- Add wordlist type to selection forms, to improve user experience
=> Improve wordlists management

rekono/frontend/src/common/TableHeader.vue, rekono/frontend/src/components/Processes.vue, rekono/frontend/src/components/Tools.vue, rekono/frontend/src/components/Wordlists.vue
Use checkbox instead of select form to filter resources by user likes
=> Improve resources filter by likes in web UI

rekono/tools/fixtures/3_configurations.json
=> Configure CMSeeK to don't ask user for anything

rekono/tools/tools/base_tool.py
=> Fix application of environment variables in tool execution

rekono/tasks/models.py, rekono/tools/tools/base_tool.py
=> Save skipped reason in output plain field

README.md, docker/nginx/nginx.conf, rekono/frontend/src/modals/Process.vue, rekono/frontend/src/modals/Step.vue, rekono/frontend/src/modals/Task.vue, rekono/frontend/vue.config.js, rekono/tools/fixtures/1_tools.json
- Add GitHub and Discord icons to the README
- Change icons for Nuclei, FullHunt tools and GitLeaks, to fit properly in web UI
=> Fix icons in README and UI

docker/rekono/Dockerfile, rekono/frontend/package-lock.json, rekono/frontend/package.json
=> Fix unsupported dependency in Node 19 and fix npm install in Dockerfile

.github/workflows/desktop-applications.yml, .github/workflows/security-sast.yml, .github/workflows/security-secrets.yml, .semgrepignore, rekono/email_notifications/sender.py, rekono/email_notifications/templates/execution_notification.html, rekono/email_notifications/templates/user_enable_account.html, rekono/email_notifications/templates/user_invitation.html, rekono/email_notifications/templates/user_login_notification.html, rekono/email_notifications/templates/user_password_reset.html, rekono/email_notifications/templates/user_telegram_linked_notification.html, rekono/input_types/utils.py, rekono/rekono/settings.py, rekono/tools/tools/nikto.py, rekono/tools/tools/sslscan.py, rekono/tools/tools/zap.py, rekono/tools/utils.py, rekono/users/serializers.py, requirements.txt, sonar-project.properties
=> Scan code using Semgrep

requirements.txt
=> Upgrade Django to version 3.2.18

docker/rekono/Dockerfile, rekono/frontend/package-lock.json, rekono/frontend/package.json
=> Upgrade node-ipc version to 9.2.6 to fix Node 19 incompatibilities

CHANGELOG.md, rekono/frontend/package.json, rekono/rekono/settings.py, rekono/resources/apps.py, rekono/system/apps.py, rekono/tools/apps.py
=> Prevent default data loading from fixtures when user data exists

rekono/frontend/src/components/Wordlists.vue, rekono/frontend/src/modals/Task.vue, rekono/frontend/src/modals/Wordlist.vue, rekono/resources/urls.py, rekono/testing/api/test_resources.py
=> Change Wordlists endpoint to /api/wordlists/

.gitignore, docker-compose.yml, docker/README.md, docker/nginx/Dockerfile, docker/nginx/entrypoint.sh, docker/nginx/nginx.conf, docker/nginx/tls/README.md
=> Support for custom TLS configuration in Docker environments

.github/workflows/desktop-applications.yml, config.yaml, docker-compose.yml
=> Improve Docker compose configuration

config.yaml, docker-compose.yml, docker/rekono/Dockerfile.backend, docker/rekono/Dockerfile.frontend, rekono/frontend/src/backend/RekonoApi.vue, rekono/rekono/config.py, rekono/rekono/environment.py, rekono/rekono/settings.py, requirements.txt
=> Add support to expose API Rest in specific root path via reverse proxy

CHANGELOG.md, docker/kali/Dockerfile, rekono/frontend/package.json, rekono/rekono/settings.py
=> Replace kali-rolling image by kali-last-release

.github/workflows/desktop-applications.yml
=> Fix upload of Windows Desktop app to GitHub releases

rekono/testing/api/test_users.py
=> chore: update test_users.py

src/backend/findings/framework/models.py, src/backend/framework/models.py, src/backend/framework/platforms.py, src/backend/framework/queues.py, src/backend/parameters/filters.py, src/backend/parameters/framework/models.py, src/backend/parameters/framework/serializers.py, src/backend/parameters/framework/views.py, src/backend/parameters/models.py, src/backend/parameters/serializers.py, src/backend/parameters/views.py, src/backend/platforms/telegram_app/bot/conversations.py, src/backend/platforms/telegram_app/bot/enums.py, src/backend/platforms/telegram_app/bot/mixins/parameters.py, src/backend/platforms/telegram_app/bot/mixins/tasks.py, src/backend/platforms/telegram_app/bot/mixins/wordlists.py, src/backend/projects/models.py, src/backend/reporting/models.py, src/backend/security/authorization/permissions.py, src/backend/targets/serializers.py, src/backend/tasks/models.py, src/backend/tasks/queues.py, src/backend/tasks/serializers.py, src/backend/tasks/views.py, src/backend/tests/cases.py, src/backend/tests/framework.py, src/backend/tests/test_parameters.py, src/backend/tests/test_queues.py
=> Move input parameters from targets to tasks
